apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test"
  description: "test"
  annotations:
    github.com/project-slug: instinct-vfx/test
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: "team-a"
